import type { Metadata } from "next";
import { Mail } from "lucide-react";
import { submitDiagnosticIntake } from "@/app/contact/actions";
import { DiagnosticForm } from "@/components/site/diagnostic-form";
import { TRANSFORMATION_CONVERSATION } from "@/lib/offers";
import { absoluteUrl, site } from "@/lib/site";

export const metadata: Metadata = { title: "Discuss a Healthcare Transformation", description: "A focused conversation about what is changing, what is stuck, and the decision leadership needs to make.", alternates: { canonical: "/contact" }, openGraph: { title: "Discuss a Healthcare Transformation | TKO Solutions", description: "Bring the messy problem: burden, controls, dependencies, technology, and execution.", url: absoluteUrl("/contact"), images: [{ url: site.socialImage, width: 1200, height: 630, alt: "Discuss a healthcare transformation with TKO Solutions." }] } };
type SearchParams = { searchParams: Promise<{ status?: string; intent?: string }> };

export default async function ContactPage({ searchParams }: SearchParams) {
  const { status, intent } = await searchParams; const isPartner = intent === "partner";
  return <section className="py-12 md:py-16"><div className="mx-auto w-full max-w-7xl px-6 lg:px-8"><div className="max-w-[64ch]"><p className="text-sm font-semibold uppercase tracking-[0.1em] text-primary">{isPartner ? "Delivery-partner support" : "Discuss a transformation"}</p><h1 className="mt-4 text-4xl font-bold leading-[1.05] tracking-tight md:text-5xl">{isPartner ? "Describe the transformation and the capability gap." : "Bring the messy problem."}</h1><p className="mt-5 text-lg leading-8 text-muted">{isPartner ? "For consultancies, integrators, and internal delivery organizations that need principal-level healthcare operating-model, dependency, governance, or implementation depth." : "What is changing? What is stuck? Where is the administrative burden? Which teams and systems are involved? Start there. I will respond within one business day and say plainly whether I am the right help."}</p></div>
  <div className="mt-10 grid gap-x-12 gap-y-8 lg:grid-cols-[0.7fr_1.3fr]"><aside><h2 className="text-xl font-semibold">What happens next</h2><ol className="mt-5 space-y-4 text-base leading-7 text-muted"><li><span className="font-semibold text-foreground">1.</span> I read every submission personally.</li><li><span className="font-semibold text-foreground">2.</span> If the problem is plausible and conflict-free, I reply within one business day.</li><li><span className="font-semibold text-foreground">3.</span> A 45-minute working conversation tests the problem boundary, sponsor, evidence, urgency, and decision required.</li><li><span className="font-semibold text-foreground">4.</span> I recommend the smallest useful paid diagnostic—or say directly that TKO is not the right fit.</li></ol><div className="mt-8 border-l-2 border-primary bg-surface p-5"><p className="text-sm font-semibold uppercase tracking-[0.1em] text-primary">Scope of the conversation</p><p className="mt-3 text-sm leading-6 text-muted">{TRANSFORMATION_CONVERSATION.boundary}</p></div></aside>
  <div>{status === "submitted" ? <Notice title="Request received." body="I will respond within one business day. If there is a plausible fit, the next step is a focused working conversation—not a generic sales presentation." /> : null}{status === "invalid" ? <Notice title="More detail is required." body="Complete the required fields and describe the operating or transformation problem with enough detail to qualify it." /> : null}{status === "error" ? <Notice title="The request could not be submitted." body="Please try again or email me without including patient or other sensitive information." /> : null}{status === "notification-error" ? <Notice title="Your request was saved, but the notification could not be confirmed." body="Please email me directly so the request is not missed." /> : null}<DiagnosticForm action={submitDiagnosticIntake} status={status} /><p className="mt-8 border-t border-border pt-6 text-sm leading-6 text-muted">Prefer email? Write to me at <a href={`mailto:${site.email}`} data-conversion-event="email_link_click" data-cta-location="contact_page" data-cta-label="email" className="inline-flex items-center gap-1 font-semibold text-foreground hover:text-primary hover:underline"><Mail className="size-4" aria-hidden />{site.email}</a>. Do not send sensitive or patient information.</p></div></div></div></section>;
}

function Notice({ title, body }: { title: string; body: string }) { return <div className="mb-6 rounded-md border border-primary/30 border-l-4 border-l-primary bg-surface p-5"><p className="font-semibold">{title}</p><p className="mt-2 text-sm leading-6 text-muted">{body}</p></div>; }
