import type { Metadata } from "next";
import { ExternalLink } from "lucide-react";
import { CtaBand } from "@/components/site/cta-band";
import { JsonLd } from "@/components/site/json-ld";
import { PageHero } from "@/components/site/page-hero";
import { Section, SectionHeader } from "@/components/ui/section";
import { careerTimeline, executiveSummary, founderArchetypes, howIWork } from "@/lib/founder";
import { absoluteUrl, site } from "@/lib/site";

export const metadata: Metadata = { title: "Todd Kovalsky | Healthcare Transformation & Operating Model Strategist", description: "Todd Kovalsky structures complex, regulated healthcare change across operations, technology, controls, governance, and implementation.", alternates: { canonical: "/founder" }, openGraph: { title: "Todd Kovalsky | Healthcare Transformation & Operating Model Strategist", description: "Strategist, translator, orchestrator, and operator behind TKO Solutions.", url: absoluteUrl("/founder"), images: [{ url: site.socialImage, width: 1200, height: 630, alt: "Todd Kovalsky, founder of TKO Solutions." }] } };

export default function FounderPage() {
  return (
    <>
      <JsonLd data={{ "@context": "https://schema.org", "@type": "ProfilePage", name: "Todd Kovalsky", url: absoluteUrl("/founder"), mainEntity: { "@type": "Person", name: "Todd Kovalsky", jobTitle: "Healthcare Transformation & Operating Model Strategist", worksFor: { "@type": "Organization", name: site.name, url: site.url }, sameAs: [site.linkedin], knowsAbout: ["Healthcare Transformation", "Operating Model Design", "Provider Operations", "Prior Authorization", "Utilization Management", "Governed AI"] } }} />
      <PageHero eyebrow="Founder & principal" title={executiveSummary.headline} description="I help healthcare organizations translate complex operational change into executable operating models, technology roadmaps, and transformation programs—particularly where regulation, administrative burden, provider experience, and enterprise technology collide." primaryHref="/contact" primaryLabel="Discuss a Transformation" secondaryHref="/selected-work" secondaryLabel="Review the Evidence" />

      <Section className="bg-surface !py-12 md:!py-16"><div className="grid gap-3 md:grid-cols-2">{executiveSummary.facts.map((fact) => <p key={fact} className="border-l-2 border-primary bg-white p-5 text-sm leading-6 text-muted">{fact}</p>)}</div></Section>

      <Section><SectionHeader eyebrow="Professional archetype" title="Strategist + Translator + Orchestrator + Operator" description="The highest-value capability is not generic program management. It is structuring complexity across the boundaries where transformations fail." /><div className="mt-10 border-t border-border">{founderArchetypes.map((item, index) => <article key={item.title} className="grid gap-4 border-b border-border py-7 md:grid-cols-[3rem_0.65fr_1.35fr]"><span className="font-mono text-sm text-primary">0{index + 1}</span><h2 className="text-2xl font-semibold">{item.title}</h2><p className="text-base leading-7 text-muted">{item.body}</p></article>)}</div></Section>

      <Section className="bg-surface"><div className="grid gap-12 lg:grid-cols-[0.8fr_1.2fr]"><SectionHeader eyebrow="The recurring pattern" title="From fragmented complexity to integrated execution." description="Executive objectives become many teams, applications, requirements, releases, constraints, and unclear dependencies. Todd builds the structures that let leaders see and govern the whole." /><div className="grid gap-6 sm:grid-cols-2"><div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-muted">Starting condition</p><p className="mt-4 text-base leading-7 text-muted">Many stakeholders. Multiple programs. Changing requirements. Fragmented ownership. No integrated truth.</p></div><div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-primary">What Todd creates</p><p className="mt-4 text-base leading-7">Workstreams. Dependency visibility. Governance. Decision structures. Escalation. Readiness. Accountability. Implementation sequence.</p></div></div></div></Section>

      <Section><SectionHeader eyebrow="Career record" title="What each chapter contributes." description="Employment history establishes experience, not employer or client endorsement." /><ol className="mt-10 border-l-2 border-border">{careerTimeline.map((entry) => <li key={`${entry.years}-${entry.organization}`} className="relative pb-10 pl-8 last:pb-0"><span aria-hidden className="absolute -left-[7px] top-1.5 size-3 rounded-full border-2 border-primary bg-white" /><p className="text-xs font-semibold uppercase tracking-[0.14em] text-muted">{entry.years} · {entry.era}</p><h2 className="mt-2 text-xl font-semibold">{entry.organization}</h2><p className="mt-1 text-sm font-semibold text-primary">{entry.role}</p><p className="mt-3 max-w-[72ch] text-base leading-7 text-muted">{entry.scope}</p><p className="mt-3 max-w-[72ch] text-sm leading-6"><span className="font-semibold text-primary">Buyer relevance: </span>{entry.buyerRelevance}</p></li>)}</ol><a href={site.linkedin} target="_blank" rel="noreferrer" data-conversion-event="linkedin_click" data-cta-location="founder" data-cta-label="LinkedIn" className="mt-10 inline-flex min-h-11 items-center gap-2 border border-border px-5 text-sm font-semibold uppercase tracking-[0.08em] hover:border-primary hover:text-primary">Review LinkedIn <ExternalLink className="size-4" aria-hidden /></a></Section>

      <Section className="bg-surface"><SectionHeader eyebrow="How I work" title="Principal attention, explicit boundaries." /><div className="mt-10 grid gap-4 md:grid-cols-2">{howIWork.map((item) => <article key={item.title} className="border border-border bg-white p-6"><h2 className="text-xl font-semibold">{item.title}</h2><p className="mt-3 text-base leading-7 text-muted">{item.body}</p></article>)}</div></Section>
      <CtaBand title="Talk to the person who will do the work." description="Start with the operating problem and the decision leadership needs to make." primaryLabel="Discuss a Transformation" secondaryHref="/services" secondaryLabel="Compare Engagements" />
    </>
  );
}
